spring:
  dubbo:
   application:
     name: provider
   registry:
     address: zookeeper://106.12.203.66:2181
   protocol:
    name: dubbo
    port: 8880
   scan:  org.spring.springboot.dubbo
  data:
    mongodb:
      uri: mongodb://gzcc:jsjs137139@caixiaoshan.club:27017/bill
# username: authmanager
#     password: hopnetworks
#     database: dota2data
#      authentication-database: dota2data
server:
  port:  8889

#  106.12.203.66*